const GAME_EVENT = {
STEP:'STEP',BUMP:'BUMP',BLOCKED:'BLOCKED',NEAR:'NEAR',GATE_OPEN:'GATE_OPEN',KERNEL_OPEN:'KERNEL_OPEN',
CACHE:'CACHE',JACK_IN:'JACK_IN',CHIP_ADD:'CHIP_ADD',CHIP_REMOVE:'CHIP_REMOVE',LINE_CLEAR:'LINE_CLEAR',
PROBE:'PROBE',BREACH:'BREACH',TRACE:'TRACE',TRACED:'TRACED',ACCEPTED:'ACCEPTED',STAR:'STAR',XP:'XP',
LEVEL_UP:'LEVEL_UP',SECTOR_CLEAR:'SECTOR_CLEAR',EXPLOIT:'EXPLOIT',DISCONNECT:'DISCONNECT',ENDING:'ENDING',
SHOW_LINE:'SHOW_LINE',
};

export { GAME_EVENT };
