name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    env:
        GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install
        
      - name: 1 .env create for build not to crush
        run: echo 'FIREBASE_API_KEY="YOUR-API-KEY"' >> .env
        
      - name: 2 .env create for build not to crush
        run: echo 'FIREBASE_PROJECT_ID="YOUR-PROJECT-ID"' >> .env
        
      - name: 3 .env create for build not to crush
        run: echo 'FIREBASE_APP_ID="YOUR-APP-ID"' >> .env

      - name: Generate
        run: yarn run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
